runtime: nodejs20  # Ensure you are using a supported Node.js version

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

service: backend  # Unique service name for the backend

handlers:
  - url: /.*
    script: auto  # Use this if your backend is a Node.js server

env_variables:
  NODE_ENV: production